language: node_js
cache:
  apt: true
  directories:
  - node_modules
  - bower_components
  - "$HOME/.npm"
node_js:
- '8'
install:
- npm install -g bower polymer-cli firebase-tools sentry-cli-binary
- bower install
- npm install
before_script:
- test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && ./travis/before_script.sh
script:
- xvfb-run npm run test
after_success:
- test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && ./travis/after_success.sh
notifications:
  slack:
    rooms:
      secure: ORT9RjcIt+YNpeVs3ngULB5qVoY7snPGTDXfPE6DvxO+i5N8XKD2poccehlJW3Z1D1N6MnjGY8uhpFNCEJokMvYlVuxjnWnZJMWXaOCIYLRDdcfQY8inEb/aZIsgDeIy4JAbhmp+SGVmS3pvIPwg5QqAr1rB0NOiPINocnQveU1x7e77KGCtkyXS3Oa2MkCap1sAKoKy78QTP+CDVID3sZja4mtK2+eNm/B5Dh5+UhAPGb3bmV7V5Dunw4uFtAhebUGlBYqlW7WM88wIzvMysNe9g1eGgRNiGW75v4JOg4pNy2l8jDErQXxEwCKT/D3Ycnrga/NytC4fMVFLdJPX2YXwELfN7uCy3kq2s2w/3XvJCTdOfp9yDYIZkTKkeP/6X0NIJvMZZULy+OQd+QWpk8gE2ZrX4ThS/OhpQvlQKXaBJPAV1W+KoeExrlP4EFjxeg03tGExWhlsm/0Nafjx2bMrWOGf/iX2291gU7yAJnDfNn0cuPYHIlc5zUzkxzjkiOFzFbBUwUaUyTkCNKKWxNlRcCj9iBbocQTkMV/PKw6J+SFuMvBob9v8lJnbtBpoB549mCzFj1aZe3nr8SqxibayiQVNXHOj6BDgwQjPfl91XKJuUQ1eB5v+VNxwKjRd4ntk8R/UhBjha31RSFVo3FTGnS1H0uMlynjF7f6mNQo=
    on_success: change
    on_failure: always
    on_pull_requests: false
